# Generated by Django 4.2.19 on 2025-03-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('length', models.CharField(max_length=50)),
                ('circuit_type', models.CharField(max_length=50)),
                ('designer', models.CharField(max_length=50)),
                ('year_built', models.IntegerField()),
                ('circuit_image_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=50)),
                ('is_engine_manufacturer', models.BooleanField()),
                ('about', models.CharField(max_length=255)),
                ('constructor_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('driver_image_url', models.URLField()),
                ('current_constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.constructor')),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('flag_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=125, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('favorite_circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulanerdapi.circuit')),
                ('favorite_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulanerdapi.driver')),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulanerdapi.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('distance', models.CharField(max_length=25)),
                ('laps', models.IntegerField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.circuit')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.nation')),
                ('p2_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place_finishes', to='formulanerdapi.driver')),
                ('p3_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place_finishes', to='formulanerdapi.driver')),
                ('winner_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='formulanerdapi.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverConstructorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.nation'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.nation'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulanerdapi.nation'),
        ),
    ]
