# Generated by Django 4.2.19 on 2025-03-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulanerdapi', '0002_alter_driver_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='is_engine_manufacturer',
            field=models.BooleanField(default=False),
        ),
    ]
